import { Header } from '@/components/header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Stoke } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const stoke = Stoke({
  subsets: ['latin'],
  weight: '300',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='antialiased'>
      <body className={stoke.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
